config/routes.rb
Rails.application.routes.draw do
  
  resources :events
  mount Ckeditor::Engine => '/ckeditor'
  
  resources :uploads
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :pages, only: [:show]
  namespace :admin do 
    resources :pages
    resources :roles, only: [:new, :create, :destroy, :index, :show]# admin/roles
    resources :posts
    resources :users, only: [:new, :create, :destroy, :index, :show]
  end
  resources :posts  
  
  get 'tags/:tag', to: 'posts#index', as: "tag"
  get 'categories/:category', to: 'posts#index', as: "category"
  
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'
  

  root 'pages#index'
  
  get  '/signup', to: 'users#new'
  get  '/login', to: 'sessions#new'
  post  '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  get  '/wikiSearch', to: 'pages#wikiSearch'

   
  resources :pages, path: ''

 
  
end

app/views/admin/pages/_form.html.erb
 <%= form_for(["admin", @page]) do |f| %>
 <% if @page.errors.any?  %>
    <div>
      <h2><%= pluralize(@page.errors.count, "error") %> prevented from saving</h2>
      <ul>
        <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <%end%>
      </ul>
    </div>
  <%end%>
 
  <main id="main-content">
    <div class="usa-width-three-fourths">
      <div class="field">
        <%= f.label :title, :style=>"margin-top: 0;"%>
        <%= f.text_field :title %>
      </div>
    
      <div class="field">
        <%= f.label :body %>
        <%= f.cktext_area :body %>
      </div>
      
      <div class="field" id="wikiNav">
        <%= f.label "Wiki Navigation" %>
        <%= f.cktext_area :wikiNav %>
      </div>
    
      <div class="field">
        <%= f.label :slug %>
        <%= f.text_field :slug %>
      </div>

      <div class="actions">
        <%= f.submit %>
      </div>
      
      
      <%= link_to 'Back', admin_pages_path %>
    </div>  
    
    <div class="usa-width-one-fourth">
      
    <div class="panel panel-default">
      <div class="panel-heading">
          <i class="fa fa-bar-chart-o fa-fw"></i> Status
      </div>
      <div class="panel-body">
        
        <% if controller_name == 'pages' && action_name == 'edit' %>
          <label>Published At</label><br>
          <%= @page.created_at.strftime("%B %d, %Y at %l:%M %p") %> <br>
        <% end %>  

        <label>Visibility</label><br>
        <div class="btn-group" data-toggle="buttons">
          <div class="btn btn-primary <%= 'active' if @page.private == false %>">Public
          <%= f.radio_button :private, false%>
          </div> 
          <div class="btn btn-primary <%= 'active' if @page.private == true %>">Private
          <%= f.radio_button :private, true %>
          </div> 
        </div>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <i class="fa fa-folder-open" aria-hidden="true"></i> Template
      </div>
      <div class="panel-body">
        <br>
        <%= f.select :template, ['Default','File Directory','Training Portal', 'Wiki'], :id => "templateOptions" %>
        <div id="directory-folder">
          <%= f.label :fileFolder, "Enter Default Folder" %>
          <%= f.text_field :fileFolder %>
        </div>
      </div>     
    </div>
  </div>
</main>
<% end %>

<script>


$(document).ready( function () {
  
  var t = "<%= @page.template %>"
  if (t == "File Directory") {
    $('#directory-folder').show();
  } else {
    $('#directory-folder').hide();
  }
  if (t == "Wiki") {
    $('#wikiNav').show();
  } else {
    $('#wikiNav').hide();
  }
  
  $("#page_template").change(function() {
    var val = $(this).val();

    if(val === "File Directory") {
      $("#directory-folder").show();
    }
    else {
      $("#directory-folder").hide();
    }
    if(val === "Wiki") {
      $("#wikiNav").show();
    }
    else {
      $("#wikiNav").hide();
    }
  });
});
</script>


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<style>
  @media screen and (min-width: 600px) {
    .usa-width-three-fourths {
      width: 68.41059%;
      margin-right: 4.35765%;
    }
    
    .usa-width-one-fourth:nth-child(2n) {
      width: 27.23176%;
    }
  }

  input, textarea, select {
    margin: 0;
    max-width: 70rem;
  }
  
  .col-sm-6 {
    padding-left: 0;
  }
  
  .btn-primary {
    background-color: grey;
    border-color: #747e88;
  }
  
  .btn:focus, .btn.focus, .btn:active:focus, .btn:active.focus, .btn.active:focus, .btn.active.focus {
    outline: none;
    outline: none; 
    outline-offset: none;
  }
  
  .panel-body {
    padding: 0 15px 15px 15px;
    font-size: 16px;
  }
</style>

app/views/admin/pages/edit.html.erb
<main class="usa-grid usa-section" id="main-content">
    <h1>Editing Page</h1>
    
    <%= render 'form', page: @page %>
    
</main>

app/views/admin/pages/index.html.erb
<main class="usa-grid usa-section" id="main-content">
<h1>Pages</h1>


      <table class="table-bordered dataTables_wrapper dt-responsive">
        <thead>
          <tr>
            <th>Title</th>
            <th>Slug</th>
            <th>Show</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
        </thead>
      
        <tbody>
          <% @pages.each do |page| %>
            <tr>
              <td><%= page.title %> <% if page.private == true%> <span style="color:orange"> - private page</span><%end%></td>
              <td><%= page.slug %></td>
              <td><%= link_to 'Show', page_path(page) %></td>
              <td><%= link_to 'Edit', edit_admin_page_path(page) %></td>
              <td><%= link_to 'Destroy', admin_page_path(page), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>


<%= button_to 'New Page', new_admin_page_path, :method => :get %>

<script>
  $('table').DataTable();

// See:
// http://www.sitepoint.com/responsive-data-tables-comprehensive-list-solutions
</script>
<style>
  .dataTables_wrapper .dataTables_paginate .paginate_button {

    padding: 0;
    margin-left: 0px; 

  }
  
  select {
    -webkit-appearance: menulist;
    box-sizing: border-box;
    align-items: center;
    white-space: pre;
    -webkit-rtl-ordering: logical;
    color: black;
    background-color: white;
    cursor: default;
    border-width: 1px;
    border-style: solid;
    border-color: initial;
    border-image: initial;
}

.dataTables_wrapper .dataTables_paginate .paginate_button:hover {
  background-color: none;
  border: 1px solid #f1f1f1;
  background: none;
}

</style>

</main>

app/views/admin/pages/new.html.erb
<main class="usa-grid usa-section" id="main-content">
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', admin_pages_path %>
</main>

app/views/admin/pages/show.html.erb
<main class="usa-grid usa-section" id="main-content">

  <p>
    <strong>Title:</strong>
    <%= @page.title %>
  </p>
  
  <p>
    <strong>Body:</strong>
    <%= simple_format(@page.body) %>
  </p>
  
  <p>
    <strong>Slug:</strong>
    <%= @page.slug %>
  </p>
  
  <%= link_to 'Edit', edit_admin_page_path(@page) %> |
  <%= link_to 'Back', admin_pages_path %>
</main>