config/routes.rb
Rails.application.routes.draw do
  
  resources :events
  mount Ckeditor::Engine => '/ckeditor'
  
  resources :uploads
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :pages, only: [:show]
  namespace :admin do 
    resources :pages
    resources :roles, only: [:new, :create, :destroy, :index, :show]# admin/roles
    resources :posts
    resources :users, only: [:new, :create, :destroy, :index, :show]
  end
  resources :posts  
  
  get 'tags/:tag', to: 'posts#index', as: "tag"
  get 'categories/:category', to: 'posts#index', as: "category"
  
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'
  

  root 'pages#index'
  
  get  '/signup', to: 'users#new'
  get  '/login', to: 'sessions#new'
  post  '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  get  '/wikiSearch', to: 'pages#wikiSearch'

   
  resources :pages, path: ''

 
  
end

app/models/upload.rb
class Upload < ActiveRecord::Base
   mount_uploader :name, FileUploader
   
  
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :set_upload, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:new, :show, :index, :edit, :update, :destroy]
  before_action :check_role, only: [:new, :edit, :update, :destroy, :index]
  before_action :check_params, only: [:create]
  
 
  # GET /uploads
  def index
    @uploads = Upload.all
  end
 
  # GET /uploads/1
  def show
    @upload = Upload.find(params[:id])
    #redirect_to @upload.name.file.authenticated_url
  end
 
  # GET /uploads/new
  def new
    @upload = Upload.new
    @uploads = Upload.all
    
    u = Upload.all
    @upload_paths = u.map { 
      |upload| encoded_url = URI.encode(upload.name.path) 
      url = URI(encoded_url).path.split('/').fourth
      URI(encoded_url).path.split('/')[4..-1].each do |i|
        if i != URI(encoded_url).path.split('/').last 
          if has_number?(i) == false
          end
        end
      end
      URI(url)
    }.uniq
  end
 
  # GET /uploads/1/edit
  def edit
  end
 
  # POST /uploads
  def create
    
    #change parama to new directory if it is not empty
    check_params
    if params[:new_directory].blank? == false 
    params[:upload][:directory] = params[:new_directory]
    end
    
    @upload = Upload.new(post_upload_params)
    if @upload.save
      redirect_to :back, notice: 'Upload was successfully created.'
    else
      render :new
    end
  end
 
  # PATCH/PUT /uploads/1
  def update
    if @upload.update(post_upload_params)
      redirect_to uploads_url, notice: 'Upload attachment was successfully updated.'
      
    else
      render :edit
    end
  end
 
  # DELETE /uploads/1
  def destroy
    @upload.destroy
    redirect_to :back, notice: 'File was successfully destroyed.'
  end
 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upload
      @upload = Upload.find(params[:id])
    end
 
    # Never trust parameters from the scary internet, only allow the white list through.
    def post_upload_params
        params.require(:upload).permit(:name, :directory)
    end
      
      
    
    #check and make sure it user is site admin before giving access 
    def check_role
      redirect_to(root_url) unless check_role?("Document Editor") or check_role?("Site Admin")
    end
    
    
    
      
    #confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger]= "Please log in."
        redirect_to login_path
        
      end
    end
    
    def check_params
      if params[:upload][:name] == nil
        flash[:danger] = "Please make sure a file is selected"
        
        redirect_to :controller => "uploads", :action =>"new"
      end
    end
    
    #check if a string only contains number, if yes return true or else false
    def has_number?(i)
      if /^(?<num>\d+)$/ =~ i
        true
      else
        false
      end
    end
    
   
end

app/views/uploads/index.html.erb
<main class="usa-grid usa-section" id="main-content">
<h1>Uploads</h1>
<table id="table_uploads" class="table-bordered dt-responsive">
  <thead>
    <tr>
      <th>Title</th>
      <th>Directory</th>
      <th>Created At</th>
      <th>Delete</th>
      <th>Created At Hidden</th>
    </tr>
  </thead>
  
  <tbody>
    <% @uploads.each do |upload| %>
    
    <tr>
      <td width="65%;">
        <%= link_to upload.name.url, target: :_blank do %>
          <%=  File.basename(upload.name.path) %>
        <% end %>
      </td>
      <td><%= upload.directory %></td>
      <td><center><%= upload.created_at.strftime("%B %d, %Y at %l:%M %p") %></center></td>
      <td width="70px;">
        <%= link_to 'Delete', upload_path(upload), data: {:confirm => 'Are you sure?'}, :method => :delete, :class => "btn btn-danger" %>
      </td>
      <td><%= upload.created_at %></td>
  </tr>
    <% end %>

  </tbody>
</table>  
<div class="button_wrapper">
<%= button_to 'New upload', new_upload_path, :method => :get %>
</div>
</main>


<script>
$(document).ready(function() {
  var table = $('#table_uploads').dataTable( {
    "order": [ 2, 'desc' ],
    "columnDefs": [
      { "orderData": 2, "targets": 4 },
      { "targets": 4, visible: false}
    ]
  } );
} );

</script>

<style>

  table td {
    -ms-word-break: break-all;
    word-break: break-all;
    word-break: break-word;
  }
  
  .dataTables_wrapper .dataTables_paginate .paginate_button {

    padding: 0;
    margin-left: 0px; 

  }
  
  a {
    text-decoration: none;
  }
  
  form [type="submit"], form [type="submit"] {
  margin-top: 0;
}

.btn-danger {
  text-decoration: none;
}

a.btn-danger:visited {
  color: #fff;
}
</style>


</main>

app/views/uploads/new.html.erb
<main class="usa-grid usa-section" id="main-content">
  <h1>New Upload</h1>
   
  <%= form_for(@upload) do |f| %>
    <% if @upload.errors.any?  %>
      <div>
        <h2><%= pluralize(@upload.errors.count, "error") %> prevented from saving</h2>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <%end%>
        </ul>
      </div>
    <%end%>
  
    <div>
      <%= f.label :name %><br>
      <%= f.file_field :name %>
    </div>
    <div id="directory-option">
      <%= f.label :directory, 'Select Existing Directory' %> <br>
      <%= f.select :directory, options_for_select(@upload_paths.map { |obj| [obj, obj] }, :selected => 'general') %>
    </div>
    
    <div id="directory-new">
       <%= f.label :new_directory  %> <br>
       <%= text_field_tag 'new_directory', nil, placeholder: 'Enter a new directory' %>
    </div>
    
    <div id="directory-new-btn">
      <a href="#" class="btn btn-warning">Create New Directory</a>
    </div>
    
    <div id="directory-cancel-btn">
      <a href="#" class="btn btn-warning">Cancel</a>
    </div>
    
    <div id="submit">
      <%= f.submit "Upload" %>
    </div>
  <% end %>
   
  <%= link_to 'Back', uploads_path %>
</main>

<style>
  a.btn.btn-warning {
    text-decoration: none;
  }
  
  a.btn.btn-warning:visited {
    color: white;
  }
  
  .btn {
    margin-top: 10px;
  }
</style>
<script>
 $(document).ready(function() {

 $('#directory-new').hide(); //Initially form wil be hidden.
 $('#directory-cancel-btn').hide(); //Initially form wil be hidden.

  $('#directory-new-btn').click(function() {
   $('#directory-new').show();//Form shows on button click
   $('#directory-option').hide();
   $('#directory-new-btn').hide();
   $('#directory-cancel-btn').show();
    return false;
   });
   
   $('#directory-cancel-btn').click(function() {
    $('#directory-option').show();
    $('#directory-new-btn').show();
    $('#directory-cancel-btn').hide();
    $('#directory-new').hide();
    return false;
   });
   
 });
</script>

app/views/uploads/show.html.erb
<%= link_to 'Destroy', @upload,  method: :delete, data: { confirm: 'Are you sure?' } %>
<img src="<%= @upload.name.url %>" /><br/>