config/routes.rb
Rails.application.routes.draw do
  
  resources :events
  mount Ckeditor::Engine => '/ckeditor'
  
  resources :uploads
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :pages, only: [:show]
  namespace :admin do 
    resources :pages
    resources :roles, only: [:new, :create, :destroy, :index, :show]# admin/roles
    resources :posts
    resources :users, only: [:new, :create, :destroy, :index, :show]
  end
  resources :posts  
  
  get 'tags/:tag', to: 'posts#index', as: "tag"
  get 'categories/:category', to: 'posts#index', as: "category"
  
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'
  

  root 'pages#index'
  
  get  '/signup', to: 'users#new'
  get  '/login', to: 'sessions#new'
  post  '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  get  '/wikiSearch', to: 'pages#wikiSearch'

   
  resources :pages, path: ''

 
  
end

app/views/layouts/_footer.html.erb
 <footer class="usa-footer usa-footer-medium" role="contentinfo">
      <div class="usa-grid usa-footer-return-to-top">
        <%= link_to("Return to top", "#")%>
        
      </div>
      <div class="usa-footer-primary-section">
        <div class="usa-grid-full">

        </div>
      </div>

      <div class="usa-footer-secondary_section">
        <div class="usa-grid">
          <div class="usa-footer-logo usa-width-one-half">
            <%= image_tag("cwds_logo.png", :alt => "Logo image", :class =>"usa-footer-circle-124" ) %>
            <h3 class="usa-footer-logo-heading">Child Welfare Digital Services</h3>
          </div>
          <div class="usa-footer-contact-links usa-width-one-half">
            <a href="https://www.facebook.com/CaliforniaCWDS/" target="_blank"><%= image_tag("img/social-icons/png/facebook.png", :size => '32x32') %></a>
            <a href="https://twitter.com/CA_CWDS" target="_blank"><%= image_tag("img/social-icons/png/twitter.png", :size => '32x32') %></a>
            <a href="https://www.linkedin.com/company/child-welfare-digital-services" target="_blank"><%= image_tag("img/social-icons/png/linkdin.png", :size => '32x32') %></a>
            <a href="https://www.youtube.com/channel/UCdoOvrtXKH1NacC4T85sADQ" target="_blank"><%= image_tag("img/social-icons/png/youtube.png", :size => '32x32') %></a>
            <a href="https://github.com/ca-cwds" target="_blank"><%= image_tag("img/social-icons/png/github.png", :size => '32x32') %></a>
            <address>
              <h3 class="usa-footer-contact-heading">CWDS Contact</h3>
              <a href="mailto:comms@cwds.ca.gov">CWDS Communications</a>
            </address>
          </div>
        </div>
      </div>
    </footer>
    
    <style>
      a:focus {
        box-shadow: none !important;
        outline: 0;
      }
    </style>

app/views/layouts/_header.html.erb
<header class="usa-header usa-header-extended" role="banner">
    <%= auto_discovery_link_tag :rss, posts_url(:format => :rss) %>
      
      <%= render 'layouts/usaBanner' %>
      
      <div class="usa-navbar">
        <button class="usa-menu-btn">Menu</button>
        <div class="usa-logo" id="logo">
          <em class="usa-logo-text">
            <%= image_tag("cwds_logo.png", :alt => "Logo image",  :size => "60" ) %>
            <a href="/" accesskey="1" title="Home" aria-label="Home">Child Welfare Digital Services</a>
            
          </em>
        </div>
      </div>
      <nav role="navigation" class="usa-nav">
        <div class="usa-nav-inner">
          <button class="usa-nav-close">
            
            <%= image_tag("img/close.svg" , :alt => "close")%>
          </button>
          <ul class="usa-nav-primary usa-accordion">
            <li>
              <%= link_to 'Follow Our Progress', 'https://cwds.ca.gov/posts', :class => "usa-nav-link"  %>
            </li>
            <li>
              <%= link_to 'Events', '/events-calendar', :class => "usa-nav-link"  %>
            </li>
            <li>
              <button class="usa-accordion-button usa-nav-link" aria-expanded="false" aria-controls="sidenav-2">
                <span>How We Operate</span>
              </button>
              <ul id="sidenav-2" class="usa-nav-submenu">
                <li>
                  <%= link_to 'How We Operate', '/how_we_operate' , :class => "usa-nav-link"  %>
                </li>

                <li>
                   <%= link_to 'Digital Service Design Standards', '/digital_service_design_standards' , :class => "usa-nav-link"  %>
                </li>
                <li>
                   <%= link_to 'Project Management', '/project_management' , :class => "usa-nav-link"  %>
                </li>
                 <li>
                    <%= link_to 'Publication Archive', '/feed' , :class => "usa-nav-link"  %>
                 </li>
                </ul>
            </li>
            <li>
              <%= link_to 'Dashboard', '/dashboard', :class => "usa-nav-link"  %>
            </li>
            <li>
              <%= link_to 'For Stakeholders', '/stakeholders', :class => "usa-nav-link", method: :get %>
            </li>
            
            <li>
              <%= link_to 'For Vendors', '/vendors', :class => "usa-nav-link"  %>
            </li>
            <li>
              <%= link_to 'About CWDS', '/about_cwds', :class => "usa-nav-link"  %>
            </li>
            
            <li>
              <%= link_to 'Careers', '/join_cwds', :class => "usa-nav-link"  %>
            </li>
            
          </ul>
          <div class="usa-nav-secondary">
            <form class="usa-search usa-search-small js-search-form">
              <div role="search">
                <label class="usa-sr-only" for="search-field-small">Search small</label>
                <input id="search-field-small" type="search" name="search">
                <button type="submit">
                  <span class="usa-sr-only">Search</span>
                </button>
              </div>
            </form>
            <ul class="usa-unstyled-list usa-nav-secondary-links">
              <li>
              <a href="http://www.hwcws.cahwnet.gov/">CWS/CMS Website</a>
            </li>
              
              
                
                
              
            </ul>
          </div>
        </div>
      </nav>
    </header>

app/views/layouts/_shim.html.erb
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />

app/views/layouts/_usaBanner.html.erb
<% if logged_in? %>
      <div class="usa-banner">
        <div class="usa-accordion">
          <header class="usa-banner-header">
            <div class="usa-grid usa-banner-inner">
            
            <%= image_tag("img/favicons/California_Flag.png", :alt => "CA Flag") %>
            <p>Welcome to CWDS: <%= current_user.name%></p>
            <button class="usa-accordion-button usa-banner-button"
              aria-expanded="true" aria-controls="gov-banner">
              <span class="usa-banner-button-text">Minimize your Dashboard</span>
            </button>
            </div>
          </header>
          <div class="usa-banner-content usa-grid usa-accordion-content" id="gov-banner">
            <div class="usa-banner-guidance-gov usa-width-one-half">
              <%= image_tag("img/icon-dot-gov.svg", :alt => "Dot gov", :class => "usa-banner-icon usa-media_block-img") %>
              <div class="usa-media_block-body">
                <p>
                  <span style="color: #10bcce; font-weight: bold;"><%= current_user.name%>'s Dashboard</span><br>
                  <strong><%= link_to "Users", admin_users_path %> | <%= link_to "Settings", edit_user_path(current_user) %> 
                  | <%= link_to "Profile", user_path(current_user) %> <% if check_role?("Site Admin") %>| <%=link_to "Role Console", admin_roles_url()%> 
                  | <%=link_to "Page Console", admin_pages_url()%> |  <%=link_to "File Manager Console", uploads_url()%>
                   <%end%> <%if check_role?("Content Editor")%>
                  | <%=link_to "Page Console", admin_pages_url()%><%end%>
                  | <%if check_role?("News Editor")%><%=link_to "Blog Console", admin_posts_url()%> <%end%>
                  </strong>
                  <br>
                 
                </p>
              </div>
            </div>
            <div class="usa-banner-guidance-ssl usa-width-one-half">
              <%= image_tag("img/icon-https.svg", :alt => "SSL", :class => "usa-banner-icon usa-media_block-img") %>
              <div class="usa-media_block-body">
               
                <p><%= link_to "Log out", logout_path, method: "delete" %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
<%else%>

<!-- Gov banner BEGIN -->
      

<%end%>

app/views/layouts/application.html.erb
<!doctype html>
  <html lang="en">
    <head>
      <title><%= full_title(yield(:title)) %>  </title>
      <%= csrf_meta_tags %>
      <%= favicon_link_tag 'favicon.ico' %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <%= render 'layouts/shim' %>
      <meta name="google-site-verification" content="NKEO7TfqceAD-XxWWC1_FoXveGXYE3FtVkevDNrUrek" />
      <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
      
        ga('create', 'UA-94107542-1', 'auto');
        ga('send', 'pageview');
      
      </script>

    </head>
    <%- if params[:controller] == 'admin/posts' or params[:controller] == 'admin/pages' or params[:controller] == 'uploads'  or params[:controller] == 'events' %>
      <body data-turbolinks="false">
    <%- else %>
      <body data-turbolinks="true">
    <%- end %>
      <!--<a class="usa-skipnav" href="#main-content">Skip to main content</a>-->
      <%= render 'layouts/header'%>
       <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
   
      <%= yield %>
     
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </body>
  </html>